from typing import List

from pydantic import BaseModel, Field


class NDAGenerationHeadingRequest(BaseModel):
    """Request schema for NDA generation tool."""

    nda_description: str = Field(..., description="User-provided description and requirements for the NDA.")
    # step: str = Field("headings", description="Step of generation: headings, add_content, refine, final")
    # prior_draft: Optional[str] = Field(None, description="Previous output from an earlier step (if applicable).")
    # headings: Optional[str] = Field(None, description="selected NDA heading.")


class NDAGenerationHeadingResponse(BaseModel):
    """Response schema for the NDA generation tool (with headings)."""

    headings: List[str] = Field(..., description="List of headings generated.")


class NDAGenerationResponse(BaseModel):
    """Response schema for NDA generation tool."""

    generated_text: str = Field(..., description="Generated NDA text for the requested step.")


class NDAContentGenerationRequest(BaseModel):
    """Request Schema for the NDA Content generation."""

    heading: str = Field(..., description="heading for which content needs to be generated.")


class NDAContentGenerationResponse(BaseModel):
    """Response Schema for the NDA content generation."""

    content: str = Field(..., description="Generated content for the given heading.")


class DraftRequest(BaseModel):
    """Input payload for the NDA drafting agent."""

    user_query: str = Field(
        ...,
        description="The user’s natural language instruction requesting an NDA clause or complete NDA draft.",
    )


class DraftLLMResponse(BaseModel):
    """Represents a single drafted NDA clause generated by the language model."""

    clause_title: str = Field(..., description="The formal contract heading of the drafted clause.")
    summary: str = Field(..., description="A brief plain-English explanation of the clause’s legal purpose.")
    content: str = Field(..., description="The full enforceable legal text of the drafted clause.")


class DraftResponse(BaseModel):
    """Structured response containing one or more drafted NDA clauses."""

    data: List[DraftLLMResponse] = Field(..., description="An ordered list of drafted clauses generated in response to the user query.")
