from typing import List

from pydantic import BaseModel, Field, field_validator


# Query request
class Query(BaseModel):
    """Individual query object."""

    query: str = Field(..., description="A rewritten query string.")


class QueryRewriterResponse(BaseModel):
    """Response schema for the query rewriter."""

    queries: List[Query] = Field(..., description="Rewritten queries as a list of query objects.")

    @field_validator("queries", mode="before")
    @classmethod
    def normalize_queries(cls, v: list) -> list:
        """Normalize queries to ensure they are Query objects."""
        if isinstance(v, list):
            return [Query(query=item) if isinstance(item, str) else item for item in v]
        return v


class DocChat(BaseModel):
    """DocChat response"""

    field_name: str = Field(..., description="The heading name of the response.")
    answer: str = Field(..., description="Answer generated by the LLM based on the document context and user query.")


class DocChatResponse(BaseModel):
    """Response schema for the document chat."""

    title: str = Field(..., description="The title for the given responses.")
    answers: List[DocChat] = Field(..., description="All the related answers for the user query.")
